/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'title' : string,
  'content' : string,
  'published' : boolean,
  'tags' : Array<string>,
  'publishedAt' : Time,
  'author' : string,
  'imageUrl' : [] | [string],
}
export interface ContactMessage {
  'subject' : string,
  'name' : string,
  'read' : boolean,
  'email' : string,
  'message' : string,
}
export interface Event {
  'title' : string,
  'date' : Time,
  'description' : string,
  'imageUrl' : [] | [string],
  'registrationOpen' : boolean,
  'location' : string,
  'eventType' : string,
}
export interface EventRegistration {
  'eventId' : string,
  'branch' : string,
  'name' : string,
  'year' : bigint,
  'email' : string,
}
export interface GalleryItem {
  'imageUrl' : [] | [string],
  'caption' : string,
  'blobId' : [] | [string],
}
export interface TeamMember {
  'bio' : string,
  'sortOrder' : bigint,
  'name' : string,
  'role' : string,
  'githubUrl' : [] | [string],
  'imageUrl' : [] | [string],
  'linkedinUrl' : [] | [string],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<[GalleryItem], undefined>,
  'addTeamMember' : ActorMethod<[TeamMember], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[BlogPost], undefined>,
  'createEvent' : ActorMethod<[Event], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllRegistrations' : ActorMethod<[], Array<EventRegistration>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getGallery' : ActorMethod<[], Array<GalleryItem>>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageRead' : ActorMethod<[string], undefined>,
  'registerForEvent' : ActorMethod<[EventRegistration], undefined>,
  'removeGalleryItem' : ActorMethod<[string], undefined>,
  'removeTeamMember' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'updateBlogPost' : ActorMethod<[string, BlogPost], undefined>,
  'updateEvent' : ActorMethod<[string, Event], undefined>,
  'updateTeamMember' : ActorMethod<[string, TeamMember], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];