/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GalleryItem = IDL.Record({
  'imageUrl' : IDL.Opt(IDL.Text),
  'caption' : IDL.Text,
  'blobId' : IDL.Opt(IDL.Text),
});
export const TeamMember = IDL.Record({
  'bio' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'githubUrl' : IDL.Opt(IDL.Text),
  'imageUrl' : IDL.Opt(IDL.Text),
  'linkedinUrl' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : Time,
  'author' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const Event = IDL.Record({
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'registrationOpen' : IDL.Bool,
  'location' : IDL.Text,
  'eventType' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'read' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const EventRegistration = IDL.Record({
  'eventId' : IDL.Text,
  'branch' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'email' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryItem' : IDL.Func([GalleryItem], [], []),
  'addTeamMember' : IDL.Func([TeamMember], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func([BlogPost], [], []),
  'createEvent' : IDL.Func([Event], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(EventRegistration)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getGallery' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessageRead' : IDL.Func([IDL.Text], [], []),
  'registerForEvent' : IDL.Func([EventRegistration], [], []),
  'removeGalleryItem' : IDL.Func([IDL.Text], [], []),
  'removeTeamMember' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func([ContactMessage], [], []),
  'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [], []),
  'updateEvent' : IDL.Func([IDL.Text, Event], [], []),
  'updateTeamMember' : IDL.Func([IDL.Text, TeamMember], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GalleryItem = IDL.Record({
    'imageUrl' : IDL.Opt(IDL.Text),
    'caption' : IDL.Text,
    'blobId' : IDL.Opt(IDL.Text),
  });
  const TeamMember = IDL.Record({
    'bio' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'githubUrl' : IDL.Opt(IDL.Text),
    'imageUrl' : IDL.Opt(IDL.Text),
    'linkedinUrl' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : Time,
    'author' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const Event = IDL.Record({
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'registrationOpen' : IDL.Bool,
    'location' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'read' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const EventRegistration = IDL.Record({
    'eventId' : IDL.Text,
    'branch' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'email' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryItem' : IDL.Func([GalleryItem], [], []),
    'addTeamMember' : IDL.Func([TeamMember], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func([BlogPost], [], []),
    'createEvent' : IDL.Func([Event], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllRegistrations' : IDL.Func(
        [],
        [IDL.Vec(EventRegistration)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getGallery' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessageRead' : IDL.Func([IDL.Text], [], []),
    'registerForEvent' : IDL.Func([EventRegistration], [], []),
    'removeGalleryItem' : IDL.Func([IDL.Text], [], []),
    'removeTeamMember' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func([ContactMessage], [], []),
    'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [], []),
    'updateEvent' : IDL.Func([IDL.Text, Event], [], []),
    'updateTeamMember' : IDL.Func([IDL.Text, TeamMember], [], []),
  });
};

export const init = ({ IDL }) => { return []; };